language: java
jdk: oraclejdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
env:
  global:
  - secure: pk39hQj+Ray4UTcu5zaGufoX4vxie59rKlelFCS1YhQmbgZNHWKZlBw+QnEcGij5J43CawTzfaKh/44iTrok7LzrS3FQVJwXoX0al/wYQlgM+I9SX2CHAAFVQvODtdsDx7ULs36g5yP2ohVSC/qgIkqHL7pbESoklaUrrZuW7fdhGlfLANCNgft1HUu079eZQSeTvRwPInet4051/gNWqChw2DImxPlA5nlLgNyWYW9OiFKX2CxhDrmUl4lcJeZ4dNTE3FRtxpeW8SrkPmEiI9M0TzTmhyo/L7RHJnA/trftoA7PRHPun7M9ywSgzIZtftBz27XdKmHFl9go18XnWnVEP9N/1onQIpnt/Ec5mB2QFomKkV3UQoXvmoMPVIA52/9MA+wpDpYfsWx4S/J2kCCXJCuew7fVMp2A0UoPRQuaNLk+dYvI0pebyqqg5D3D4eGt7eq61COM9eCkeWDUTdSzYMaPe6mj0JT2H+oLR6W3lQR6LXwHhKUVFo89zLT4Axhu4SdyIE9hwnKS9yqJZfXQf2xlEs+BF5hAMQuVQlNtrxNjiSLZJuFa4scbC+NAulSpJmBa5OiijHzYpu7tWzTCZFt/kJUKKZ+wkJ1gHlnWXSiQOAditVkRtJymAsxx7eTC27U++vOjH4Mykjj7Tv0EB3iOsli0dkn8EYnIRq0=
  - secure: gMBgLZnYtm2GEiszJhTzbNOhiXCj03yTpfRBsA1fXAS3U/ThAYK4v2BF2+tvydTFqYKP5EA8wAaUo9dbZ7KTpc/f7FhbzAFkBxeDghaxFWDitW8BuuZH+gnzqD/4UaUiSgA8Bq9ljD8i47FXuj1qVR39nUKP4QDN4cV9fYyVUgn5Gv3H9Xqee1xmv0ztfvRp1PPvmzDZrK4Nl2XI1XtHdOEW5vaA3BDWwwqXg3wyzL1lSgIm457lvSL0YsoT6i9hZrVYxbwuAYP6uPSbH8uNG9DbecYRKj0WedPqluZhCY6ZVKg586+wiE7yjTEj10ZNo+jc5en/2yCovvhKUXNm+a+zD/MoDTZfH1Sxxx0sojOw3I5MQaLPL4x4mu3iq92edXohCwj32trZZdLMD3yC4rZatKpPUs9HaqT1kNqM0g06amkxMUx/WEcaz1PgLM076nVwcRyDvVO9KBTUiB6K18hr/LQ/WOh5+hFsj9lORat4XJpwKcbMfxRiRbEnBHj0q4Pe8tbXn3Xy/hqzmsfe+/6I7pwdBqqAVpJawp/bNLiRFplc+DLsEHGhCns2TqmXklE0Qbz6ZOnptIxX5XxXFTJ0cH4nx2gKjxKfxpHhWCNRwenAshbouairvpz+0Y50knVVJ9+pU2wy5g/c3jxPs4z1Frae+nYxHsXSC776wNo=
